compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - glibc
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.4.0.cjs
