compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.2.2.cjs

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - glibc
