version: 2

references:
  js_container_config: &js_container_config
    docker:
      - image: circleci/node:10
        environment:
          ENV: CI
    working_directory: ~/eliperkins-blog
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v2-repo-{{ .Branch }}-{{ .Revision }}
        - v2-repo-{{ .Branch }}
        - v2-repo
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - v2-dependency-cache-{{ .Branch }}-{{ checksum
          "yarn.lock" }}
        - v2-dependency-cache-{{ .Branch }}
        - v2-dependency-cache-master-{{ checksum "yarn.lock"
          }}
        - v2-dependency-cache-master

jobs:
  checkout-code:
    <<: *js_container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v2-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/eliperkins-blog

  build:
    <<: *js_container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Install Node Modules
          command: yarn install
      - save_cache:
          key:
            v2-dependency-cache-{{ .Branch }}-{{ checksum
            "yarn.lock" }}
          paths:
            - ~/eliperkins-blog/node_modules
            - ~/.cache/yarn

  lint:
    <<: *js_container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Run lint
          command: yarn lint

  deploy:
    <<: *js_container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Deploy to S3
          command: yarn deploy

workflows:
  version: 2
  build_lint_deploy:
    jobs:
      - checkout-code
      - build:
          requires:
            - checkout-code
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
