name: Deploy

on:
  push:
    branches: [main]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  pull-requests: read
  statuses: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Deploy
        run: yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
